name: Build and Generate SO Files

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Android NDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 21
          ndk-version: 21.4.7075529

      - name: Set up CMake
        run: sudo apt-get install -y cmake

      - name: Build for Android
        run: |
          cmake -S app/src/main -B build -DCMAKE_TOOLCHAIN_FILE=$RUNNER_TOOL_CACHE/android-ndk-21.4.7075529/cmake/android.toolchain.cmake
          cmake --build build
