- name: Build and Generate SO Files

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 21
          target: default
          arch: x86
          cores: 2
          avd-name: test
          force-avd-creation: true
          emulator-boot-timeout: 600
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          disable-animations: true
          disable-spellchecker: false
          disable-linux-hw-accel: auto
          enable-hw-keyboard: false
          channel: stable

      - name: Check adb version (optional)
        # This step is optional and will use the action-provided adb
        run: adb version

      - name: Install Android Tools (optional)
        # This step is optional as the action might already handle adb installation
        run: |
          sudo apt-get update && sudo apt-get install -y android-tools-adb

      - name: Set up CMake
        run: sudo apt-get install -y cmake

      - name: Build for Android
        run: |
          cmake -S app/src/main -B build -DCMAKE_TOOLCHAIN_FILE=$RUNNER_TOOL_CACHE/android-ndk-21.4.7075529/cmake/android.toolchain.cmake
          cmake --build build
