name: Build and Generate SO Files

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Android NDK
        uses: nakiostudio/setup-android-ndk@v2
        with:
          version: '21.4.7075529'

      - name: Set up CMake
        uses: actions/setup-cmake@v2
        with:
          cmake-version: '3.21.3'

      - name: Build for Android
        run: |
          cmake -S app/src/main -B build -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake
          cmake --build build
